name: quiz_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.2
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  cloud_firestore: ^4.7.1
  confetti: ^0.7.0
  cached_network_image: ^3.2.3
  quickalert: ^1.0.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  
  assets:
    - assets/images/splash_image.png
    - assets/images/google_icon.png
    - assets/images/splash_image1.png
    - assets/images/splash_image2.png
    - assets/images/splash_image3.png
    - assets/images/splash_image4.png
    - assets/images/win_image.jpg